### ISSUE TITLE
Mouse input broken once grained.js is added

### ISSUE THREAD

**Issue by dannymout** [sarathsaleem/grained#4]
Added grained.js to my website with the following code:

````
<script src="https://cdn.rawgit.com/sarathsaleem/grained/master/grained.js"></script>

<script>
var options = {
  "animate": true,
  "patternWidth": 600,
  "patternHeight": 600,
  "grainOpacity": 0.15,
  "grainDensity": 1,
  "grainWidth": 0.7,
  "grainHeight": 0.7,
}
grained("#hero", options);

/*
background-color :rgb(204, 204, 204)
*/
</script>
````

For some reason, custom cursor and links all broke.... Anyone else had this issue?

**Comment by arnovije** [comment]
Yes, i just fixed it myself with 'pointer-events: none' on #hero::before. Hoping this might still help you.

@sarathsaleem maybe something to add? And thanks for creation this fancyness :D

**Comment by sarathsaleem** [comment]
@dannymout @arnovije Can you provide a demo link on jsfiddle or codepen ?

**Comment by arnovije** [comment]
@sarathsaleem It was a bit of a puzzle but i managed to isolate the problem. The non-clickyness(tm) occurs when multiple layers are used. The fix for this is not entirely something which Grained.js can fix, i think. Good to know though :)

Demo: https://codepen.io/comfortstudio/pen/qBNoYdK (CSS has 2 possible fixes)

**Comment by sarathsaleem** [comment]
Thanks, @arnovije for the link. 

Yes, that kind of element structure can lead to this issue.

**From the gain readme:** https://github.com/sarathsaleem/grained#how-to-use

_Since a 'div' element with class 'grained' is added as the first child element with position absolute it will have the z index priority and appears on top of other contents in the container element. If you want the other elements in the container element on top of grained effect you have to add a css like_

`#container > * { position:relative; }`


So in the demo link as you suggest as fix 2
 `#content {
 position: relative;
}` might be an optimal fix.
